### ISSUE TITLE
Retrieve list of repo attached to organisation with space in it, silently fails

### ISSUE THREAD

**Issue by corinnekrych** [fabric8io/fabric8-generator#20]
When retrieving the list of repos under an organisation with space in the name, backed fails with 400 without returning any errors. an empty list of repos is send back to the ui
```
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.github.com/orgs/Duchess France
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:597)
	... 86 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.github.com/orgs/Duchess France
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:587)
	... 86 more
```

**Comment by jstrachan** [comment]
I think this is fixed now - it was using the Name not the login/ID of the organisation to look things up - hence the bad URL: `https://api.github.com/orgs/Duchess France`
